# Spring
spring:
  # datasource
  datasource:
    druid:
      master:
        url: jdbc:mysql://localhost:3306/matuto_boot_prod?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: prod_user # 生产环境建议使用单独的数据库用户
        password: prod_password # 生产环境密码建议使用更复杂的密码，并妥善保管
  # redis
  data:
    redis:
      host: your_redis_host
      port: 6379
      password: your_redis_password
      database: 0

# Logging
logging:
  level:
    com.matuto.boot: info # 生产环境日志级别建议设置为info
    org.springframework: warn

# 项目自定义配置
matuto:
  # 文件路径 示例（Linux配置 /home/matuto/uploadPath）
  profile: /home/matuto/uploadPath # 生产环境文件上传路径
  # 获取ip地址开关 (生产环境建议关闭，除非确实需要)
  addressEnabled: false